export const MATCH_NOT_CREATED = 0;
export const MATCH_NOT_FINISHED = 1;
export const MATCH_PLAYER_1_WON = 2;
export const MATCH_PLAYER_2_WON = 3;
export const MATCH_DRAW = 4;
export const WAITING_FOR_MATCH = 5;
export const UNKNOWN_SIGN = 0;
export const ROCK_SIGN = "1";
export const PAPER_SIGN = "2";
export const SCISSORS_SIGN = "3";
export const TIMEOUT_DURATION = 3 * 60 * 1000; // 3 minutes
