module.exports = {
  MATCH_NOT_CREATED: 0,
  MATCH_NOT_FINISHED: 1,
  MATCH_PLAYER_1_WON: 2,
  MATCH_PLAYER_2_WON: 3,
  MATCH_DRAW: 4,
  WAITING_FOR_MATCH: 5,
  UNKNOWN_SIGN: 0,
  ROCK_SIGN: 1,
  PAPER_SIGN: 2,
  SCISSORS_SIGN: 3,
  TIMEOUT_DURATION: 3 * 60 * 1000, // 3 minutes
};
